### ISSUE TITLE
update 1.0.1 broke eslint config with `"react-native/no-unused-styles": "error",`

### ISSUE THREAD

**Issue by DanielZlotin** [Intellicode/eslint-plugin-react-native#21]
with `1.0.0` everything worked,
now I get:
```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleReferencesFromContainers.getStyleReferenceFromNode (/Users/danielzl/dev/wix-one-app/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:138:17)
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleReferences (/Users/danielzl/dev/wix-one-app/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:121:23)
    at EventEmitter.unusedStyles.JSXAttribute.node (/Users/danielzl/dev/wix-one-app/node_modules/eslint-plugin-react-native/lib/rules/no-unused-styles.js:45:35)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/Users/danielzl/dev/wix-one-app/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/Users/danielzl/dev/wix-one-app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/danielzl/dev/wix-one-app/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.traverser.traverse.enter (/Users/danielzl/dev/wix-one-app/node_modules/eslint/lib/eslint.js:886:36)
    at Controller.__execute (/Users/danielzl/dev/wix-one-app/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
```

removing the line `"react-native/no-unused-styles": "error",` OR reverting to 1.0.0 fixes the issue.

**Comment by Intellicode** [comment]
Hi @DanielZlotin, apologies for breaking your code, I will fix it first thing tomorrow!

**Comment by Intellicode** [comment]
@DanielZlotin I've released a potential fix, could you verify it works for you? I've been unable to reproduce your issue locally, so I would appreciate it if you could post a test case in which it feels so it can be added to the test suite.

**Comment by DanielZlotin** [comment]
Works.
No idea how to reproduce it other than adding the mentioned line to the .lintrc
