### ISSUE TITLE
TypeError: Cannot read property 'expression' of null when use inline style

### ISSUE THREAD

**Issue by wuxiii** [Intellicode/eslint-plugin-react-native#249]
using "eslint-plugin-react": "^7.17.0","eslint-plugin-react-native": "^3.8.1"
Here's the stack trace:
```
TypeError: Cannot read property 'expression' of null
    at JSXAttribute (/Users/App/node_modules/eslint-plugin-react-native/lib/rules/no-single-element-style-arrays.js:40:24)
    at /Users/App/node_modules/eslint/lib/util/safe-emitter.js:47:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/App/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/App/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/App/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/App/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/App/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at Traverser.enter [as _enter] (/Users/App/node_modules/eslint/lib/linter.js:865:28)
    at Traverser._traverse (/Users/App/node_modules/eslint/lib/util/traverser.js:132:14)
```

**Comment by LeonardoRick** [comment]
I'm facing the same issue

**Comment by kieran-osgood** [comment]
Looking at the output you gave, which also matched mine, the problematic isn't the inline style rule but `no-single-element-style-arrays` for now I've just disabled that rule `"no-single-element-style-arrays": "off"` to avoid the error message popping up repeatedly
