### ISSUE TITLE
TypeError: this.styleSheets[styleSheetName].filter is not a function

### ISSUE THREAD

**Issue by Romick2005** [Intellicode/eslint-plugin-react-native#321]
I have in one of my file the following line:
`const hasOwnProperty = Object.prototype.hasOwnProperty;`

This cause eslint rule check to failure with error:
`TypeError: this.styleSheets[styleSheetName].filter is not a function`

```
Rule: "react-native/no-unused-styles"
    at StyleSheets.markAsUsed (/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:37:8)
    at /node_modules/eslint-plugin-react-native/lib/rules/no-unused-styles.js:57:23
    at Set.forEach (<anonymous>)
```

**Comment by Matzielab** [comment]
Not sure if it helps you or someone else, but in my case i had to lint ignore the android and ios folders
