### ISSUE TITLE
showing error when using "react-native/no-color-literals": 2

### ISSUE THREAD

**Issue by deepaksisodiya** [Intellicode/eslint-plugin-react-native#41]
<img width="1119" alt="screen shot 2016-07-20 at 6 06 55 pm" src="https://cloud.githubusercontent.com/assets/3258231/16986557/c90d0b70-4ea4-11e6-942f-c6b5462494b4.png">

**Comment by huchenme** [comment]
same here

**Comment by Intellicode** [comment]
@deepaksisodiya @huchenme Please try the new version, if possible provide a code sample that causes this crash. Most likely there are some properties in your stylesheets that are not common.

**Comment by huchenme** [comment]
actually all of 4 plugins have problem on my repo: https://github.com/huchenme/30daysOfReactNative, some are ok when run `eslint`, but problematic while using atom linter plugin, it throw errors while typing

**Comment by Intellicode** [comment]
@huchenme it will be helpful if you could post other errors related to that, I can fix them when you encounter them. If possible, mention the particular code you were typing at that point.

**Comment by antoinerousseau** [comment]
error with `no-inline-styles`:

```
Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at /usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:338:20
    at Array.forEach (native)
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleReferencesFromContainers.collectStyleObjectExpressionFromContainers.collectColorLiteralsFromContainers.getStyleObjectFromExpression.node [as getStyleObjectFromExpression] (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:337:23)
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleReferencesFromContainers.collectStyleObjectExpressionFromContainers.collectColorLiteralsFromContainers.getStyleObjectExpressionFromNode (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:267:26)
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleObjectExpressions (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:182:23)
    at EventEmitter.inlineStyles.forEach.JSXAttribute.node (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/rules/no-inline-styles.js:33:35)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
```

error with `no-color-literals`:

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at /usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:364:18
    at Array.forEach (native)
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleReferencesFromContainers.collectStyleObjectExpressionFromContainers.collectColorLiteralsFromContainers.getStyleObjectFromExpression.getColorLiteralsFromExpression.node [as getColorLiteralsFromExpression] (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:363:23)
    at Object.StyleSheets.markAsUsed.astHelpers.collectStyleReferencesFromContainers.collectStyleObjectExpressionFromContainers.collectColorLiteralsFromContainers.getColorLiteralsFromNode (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:293:26)
    at Object.StyleSheets.markAsUsed.astHelpers.collectColorLiterals (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:201:23)
    at EventEmitter.colorLiterals.forEach.VariableDeclarator.node.JSXAttribute.node (/usr/local/lib/node_modules/eslint-plugin-react-native/lib/rules/no-color-literals.js:46:37)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/usr/local/lib/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/usr/local/lib/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
```

**Comment by antoinerousseau** [comment]
I added some logging to that `stylesheet.js:364`, so in my case it happens when the parser bumps into a spread operator (eslint node type: `ExperimentalSpreadProperty`).

Example:
```jsx
<View style={{...styles.container, height: 42}}>
  {children}
</View>
```

I'm making a PR.
