### ISSUE TITLE
TypeError: Cannot read property 'type' of null

### ISSUE THREAD

**Issue by afdalwahyu** [Intellicode/eslint-plugin-react-native#92]
my error when i type style attribute:

```javascript
TypeError: Cannot read property 'type' of null
    at Object.astHelpers.hasArrayOfStyleReferences (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:312:11)
    at Object.astHelpers.collectStyleReferences (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:157:20)
    at EventEmitter.JSXAttribute (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint-plugin-react-native/lib/rules/no-unused-styles.js:46:35)
    at emitOne (events.js:95:20)
    at EventEmitter.emit (events.js:182:7)
    at NodeEventGenerator.enterNode (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/home/afdalwahyu/Documents/projects/gagclone/node_modules/eslint/lib/eslint.js:927:36)
    at Controller.__execute (/home/afdalwahyu/Documents/projects/gagclone/node_modules/estraverse/estraverse.js:397:31)
````

.eslintrc rules that make eslint show error

```javascript
  "rules": {
    ....
    "react-native/no-unused-styles": 2,
    .....
  }
````

I'm using 

> eslint-plugin-react-native@2.0.0

**Comment by Intellicode** [comment]
Sorry for the late response, can you please try the latest release?

**Comment by afdalwahyu** [comment]
Still got the same error. i'm using `yarn upgrade eslint-plugin-react-native`

**Comment by Intellicode** [comment]
Can you post your latest stacktrace? In the current code, it should be fixed at where you got the error:

https://github.com/Intellicode/eslint-plugin-react-native/blob/eslint-plugin-react-native-2.1.0/lib/util/stylesheet.js#L314

**Comment by afdalwahyu** [comment]
```javascript
TypeError: Cannot read property 'expression' of null
    at Object.collectStyleReferences (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/eslint-plugin-react-native/lib/util/stylesheet.js:167:53)
    at EventEmitter.JSXAttribute (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/eslint-plugin-react-native/lib/rules/no-unused-styles.js:46:35)
    at emitOne (events.js:101:20)
    at EventEmitter.emit (events.js:188:7)
    at NodeEventGenerator.enterNode (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/eslint/lib/util/node-event-generator.js:40:22)
    at CodePathAnalyzer.enterNode (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
    at CommentEventGenerator.enterNode (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/eslint/lib/util/comment-event-generator.js:97:23)
    at Controller.enter (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/eslint/lib/eslint.js:925:36)
    at Controller.__execute (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/home/afdalwahyu/Documents/projects/WPReactNative/node_modules/estraverse/estraverse.js:501:28)
```

i've got this error when typing `style=`

**Comment by Intellicode** [comment]
Thanks for your reply, I will investigate it, which editor do you use?

**Comment by afdalwahyu** [comment]
I'm using atom with linter & linter-eslint packages.
here is my .eslintrc file, idk maybe helpful or not :)
```javascript
{
  "extends": "airbnb",
  "env": {
    "mocha": true
  },
  "plugins": [
    "react-native"
  ],
  "globals": {
    "fetch": false
  },
  "parser": "babel-eslint",
  "rules": {
    "no-empty-label": 0,
    "no-console": 0,
    "import/no-unresolved": 0,
    "global-require": 0,
    "no-underscore-dangle": 0,
    "space-before-keywords": 0,
    "space-after-keywords": 0,
    "space-return-throw-case": 0,
    "react/prefer-stateless-function": 0,
    "react/jsx-filename-extension": 0,
    "react-native/no-unused-styles": 2,
    "react-native/split-platform-components": 2,
    "no-use-before-define": 0,
    "react/prop-types" : 0,
    "react/forbid-prop-types" : 0,
    "class-methods-use-this" : 0,
    "no-bitwise": [2, {"allow": [">>", "&"]}]
  }
}
```

**Comment by Intellicode** [comment]
I believe the latest version does not have these lines, can you check what happens for you now?

**Comment by afdalwahyu** [comment]
I'm upgrading and it's works perfectly.
I'm upgrading from 2.0.0 to 2.2.0 and it works now. 
Thanks for your good work :+1:
